name: parkmycar_client_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cloud_firestore: ^5.6.1
  equatable: ^2.0.7
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_test:
    sdk: flutter
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  mocktail: ^1.0.4
  parkmycar_shared:
    path: '../parkmycar_shared'
  provider: ^6.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0