// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0Zy2gYWBig-uLp9VtexHpOWsplt7880',
    appId: '1:605265536284:ios:0935bb0707cea9979d86d9',
    messagingSenderId: '605265536284',
    projectId: 'parkmycar-77337',
    storageBucket: 'parkmycar-77337.firebasestorage.app',
    iosBundleId: 'com.example.parkmycarUser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqu9cy4InOTlMFsANv3dbXW949pxfIdtw',
    appId: '1:605265536284:web:f0e7ccd472af14ff9d86d9',
    messagingSenderId: '605265536284',
    projectId: 'parkmycar-77337',
    authDomain: 'parkmycar-77337.firebaseapp.com',
    storageBucket: 'parkmycar-77337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0Zy2gYWBig-uLp9VtexHpOWsplt7880',
    appId: '1:605265536284:ios:0935bb0707cea9979d86d9',
    messagingSenderId: '605265536284',
    projectId: 'parkmycar-77337',
    storageBucket: 'parkmycar-77337.firebasestorage.app',
    iosBundleId: 'com.example.parkmycarUser',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNQoxRdS6vjYnifYSBd1kDUdoHApYrf0',
    appId: '1:605265536284:android:40c806c2c16d21829d86d9',
    messagingSenderId: '605265536284',
    projectId: 'parkmycar-77337',
    storageBucket: 'parkmycar-77337.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqu9cy4InOTlMFsANv3dbXW949pxfIdtw',
    appId: '1:605265536284:web:6351932adb8caba29d86d9',
    messagingSenderId: '605265536284',
    projectId: 'parkmycar-77337',
    authDomain: 'parkmycar-77337.firebaseapp.com',
    storageBucket: 'parkmycar-77337.firebasestorage.app',
  );
}
